spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/devdb
    username: devuser
    password: devpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway: 
    enabled: true

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:3001