spring:
  profiles:
    default: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls-primary-name: Semente Livre API

app:
  cors:
    allowed-origins: []
